name: floor_test
description: >
  A supportive SQLite abstraction for your Flutter applications.
  This is a module for running integration tests.
version: 0.1.0
homepage: https://github.com/vitusortner/floor
author: vitusortner

environment:
  sdk: '>=2.3.0-dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor:
    path: ../floor/

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator:
    path: ../floor_generator/
  build_runner: ^1.4.0
