name: floor_test
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  collection: ^1.14.13
  path: ^1.7.0
  sqflite: ^1.3.2+1
  sqflite_common_ffi: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test: ^0.9.0
  flutter_test:
    sdk: flutter
  floor:
    path: ../floor/
  floor_generator:
    path: ../floor_generator/
  build_runner: ^1.10.3
